name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every midnight
  workflow_dispatch:      # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Animation (Advanced)
        uses: Platane/snk@v3
        with:
          github_user_name: bhavya-data-analysis
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-colored.svg?color_snake=#32C7A7&color_dots=#FFD700
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Animation to Output Branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
          add: "dist/"
